sudo: required
dist: bionic
services: docker
language: minimal
cache:
  directories:
  - node_modules
  - "$HOME/.cache/electron"
  - "$HOME/.cache/electron-builder"
script: |
  docker run --rm \
    --env-file <(env | grep -v '\r' | grep -iE 'DEBUG|NODE_|ELECTRON_|YARN_|NPM_|CI|CIRCLE|TRAVIS|APPVEYOR_|CSC_|_TOKEN|_KEY|AWS_|STRIP|BUILD_') \
    -v ${PWD}:/project \
    -v ~/.cache/electron:/root/.cache/electron \
    -v ~/.cache/electron-builder:/root/.cache/electron-builder \
    electronuserland/builder \
    /bin/bash -c "yarn --link-duplicates --pure-lockfile && yarn release"
deploy:
  - provider: snap
    snap: dist/prospect-mail*.snap
    channel: edge
    skip_cleanup: true
    on:
      branch: develop
    # we use edge because of this: https://travis-ci.community/t/snap-deployment-stopped-working-out-of-nowhere/6908/2
    edge: true
  - provider: snap
    snap: dist/prospect-mail*.snap
    channel: stable
    skip_cleanup: true
    on:
      branch: master
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
